# Below is your Enterprise project defaults
# Each organization and repository may adjust these values below in
# their codecov.yml files. The logic used to for a project is:
# `yaml = {}; yaml.update(site); yaml.update(team_yaml); yaml.update(repo_yaml);
site:
  coverage:
    precision: 2
    round: down
    range: "10...100"
    coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "tests/"  # only include coverage in "tests/" folder
